export const translate = {
  en: {
    0: 'Home',
    1: 'Luxury packages',
    2: 'Book with us',
    3: 'Why lux trips',
    4: 'Contact',
    5: 'Call me back',
    6: 'Luxury packages',
    7: 'World',
    8: 'Uzbekistan',
    9: 'Austria',
    10: 'Winter Park Ski Holiday',
    11: 'From',
    12: 'Peru',
    13: 'Machu Picchu',
    14: 'From',
    15: 'Croatia',
    16: 'Hvar',
    17: 'From',
    18: 'Jordan',
    19: 'Ad-Deir Abbey',
    20: 'From',
    21: 'Iceland',
    22: 'Goddafos Waterfall',
    23: 'From',
    24: 'Abkhazia',
    25: 'Blue Lake',
    26: 'From',
    27: 'Indonesia',
    28: 'Bali Island',
    29: 'From',
    30: 'Iceland',
    31: 'Seljalandsfoss Waterfall',
    32: 'From',
    33: 'Italy',
    34: 'Langa Grape Fields',
    35: 'From',
    36: 'Spain',
    37: 'Barcelona',
    38: 'From',
    39: 'Nepal',
    40: 'Everest',
    41: 'From',
    42: 'San Francisco',
    43: 'Golden Gate Bridge',
    44: 'From',
    45: 'Samarqand',
    46: 'Shahi Zinda',
    47: 'From',
    48: 'Toshkent',
    49: 'Timurid`s Museum',
    50: 'From',
    51: 'Xiva',
    52: 'Kalta Minor Minaret',
    53: 'From',
    54: 'Xiva',
    55: 'Ichan-Kala',
    56: 'From',
    57: 'Xiva',
    58: ' Mausoleum of Pahlavan Mahmud',
    59: 'From',
    60: 'Buxoro',
    61: ' Samanid`s Mausoleum',
    62: 'From',
    63: 'Buxoro',
    64: 'Minaret Kalyan',
    65: 'From',
    66: 'Samarqand',
    67: 'Registan',
    68: 'From',
    69: 'Samarqand',
    70: 'Ulugbek`s Observatory ',
    71: 'From',
    72: 'Toshkent',
    73: 'Romanov`s Palace',
    74: 'From',
    75: 'Toshkent',
    76: 'Toshkent Subway',
    77: 'From',
    78: 'Toshkent',
    79: 'Madrasah Kukeldash',
    80: 'From',
    81: 'Get weekly inspiration and expert advice',
    82: ' Luxury packages',
    83: ' Book with us',
    84: ' Call me back',
    85: ' Why Lux Trips',
    86: ' Contact',
  },
  ru: {
    0: 'Главная',
    1: 'Люкс пакеты',
    2: 'Бронирование',
    3: 'Почему Lux Trip',
    4: 'Контакты',
    5: 'Связаться',
    6: 'Популярные направления',
    7: 'Мир',
    8: 'Узбекистан',
    9: 'Австрия',
    10: 'Горнолыжный отдых в Зимнем парке',
    11: 'От',
    12: 'Перу',
    13: 'Мачу-Пикчу',
    14: 'От',
    15: 'Хорватия',
    16: 'Хвар',
    17: 'От',
    18: 'Иордания',
    19: 'Аббатство Ад-Дейр',
    20: 'От',
    21: 'Исландия',
    22: 'Водопад Годдафос',
    23: 'От',
    24: 'Абхазия',
    25: 'Голубое Озеро',
    26: 'От',
    27: 'Индонезия',
    28: 'Остров Бали',
    29: 'От',
    30: 'Исландия',
    31: 'Водопад Сельяландсфосс',
    32: 'От',
    33: 'Италия',
    34: 'Виноградные поля Ланга',
    35: 'От',
    36: 'Испания',
    37: 'Барселона',
    38: 'От',
    39: 'Непал',
    40: 'Эверест',
    41: 'От',
    42: 'Сан-Франциско',
    43: 'Мост Золотые Ворота',
    44: 'От',
    45: 'Самарканд',
    46: 'Шахи Зинда',
    47: 'От',
    48: 'Ташкент',
    49: 'Музей Тимуридов',
    50: 'От',
    51: 'Хива',
    52: 'Минарет Кальта-Минор',
    53: 'От',
    54: 'Хива',
    55: 'Ичан-Кала',
    56: 'От',
    57: 'Хива',
    58: 'Мавзолей Пахлаван Махмуда',
    59: 'От',
    60: 'Бухара',
    61: 'Мавзолей Самонидов',
    62: 'От',
    63: 'Бухара',
    64: 'Минарет Калян',
    65: 'От',
    66: 'Самарканд',
    67: 'Регистан',
    68: 'От',
    69: 'Самарканд',
    70: 'Обсерватория Улугбека',
    71: 'От',
    72: 'Ташкент',
    73: 'Дворец Романовых',
    74: 'От',
    75: 'Ташкент',
    76: 'Ташкентское метро',
    77: 'От',
    78: 'Ташкент',
    79: 'Медресе Кукельдаш',
    80: 'От',
    81: 'Получать еженедельные предложения от экспертов',
    82: 'Люкс пакеты',
    83: 'Бронирование',
    84: 'Связаться',
    85: 'Почему Lux Trip',
    86: 'Контакты',
  },
  uz: {
    0: 'Bosh saxifa',
    1: 'Luxury',
    2: 'Bronlash',
    3: 'Nega Lux Trips',
    4: 'Kontaktlar',
    5: 'Qayta aloqa',
    6: 'Mashxur joylar',
    7: 'Dunyo',
    8: 'O`zbekiston',
    9: 'Avstriya',
    10: 'Qishgi parkda tatil',
    11: 'Boshlanishi',
    12: 'Peru',
    13: 'Machu Pikchu',
    14: 'Boshlanishi',
    15: 'Xorvatiya',
    16: 'Hvar',
    17: 'Boshlanishi',
    18: 'Iordan',
    19: 'Ad-Deir',
    20: 'Boshlanishi',
    21: 'Islandiya',
    22: 'Goddafos sharsharasi',
    23: 'Boshlanishi',
    24: 'Abxaziya',
    25: 'Blue Ko`l',
    26: 'Boshlanishi',
    27: 'Indonesia',
    28: 'Bali Oroli',
    29: 'Boshlanishi',
    30: 'Islandiya',
    31: 'Seljalandsfoss sharsharasi',
    32: 'Boshlanishi',
    33: 'Italiya',
    34: 'Langa Uzum Dalalari',
    35: 'Boshlanishi',
    36: 'Ispaniya',
    37: 'Barselona',
    38: 'Boshlanishi',
    39: 'Nepal',
    40: 'Everest',
    41: 'Boshlanishi',
    42: 'San-Fransisko',
    43: "Oltin Darvoza ko'prigi",
    44: 'Boshlanishi',
    45: 'Samarqand',
    46: 'Shohi Zinda',
    47: 'Boshlanishi',
    48: 'Toshkent',
    49: 'Temuridlar Muzeyi',
    50: 'Boshlanishi',
    51: 'Xiva',
    52: 'Kalta-Minor',
    53: 'Boshlanishi',
    54: 'Xiva',
    55: 'Ichon-Qal`a',
    56: 'Boshlanishi',
    57: 'Xiva',
    58: 'Pahlavon Mahmud maqbarasi',
    59: 'Boshlanishi',
    60: 'Buxoro',
    61: 'Somoniylar maqbarasi',
    62: 'Boshlanishi',
    63: 'Buxoro',
    64: 'Qalan Minorasi',
    65: 'Boshlanishi',
    66: 'Samarqand',
    67: 'Registon',
    68: 'Boshlanishi',
    69: 'Samarqand',
    70: 'Ulug‘bek Rasadxonasi',
    71: 'Boshlanishi',
    72: 'Toshkent',
    73: 'Romanovlar Saroyi',
    74: 'Boshlanishi',
    75: 'Toshkent',
    76: 'Toshkent Metrosi',
    77: 'Boshlanishi',
    78: 'Toshkent',
    79: 'Koʻkeldosh Madrasasi',
    80: 'Boshlanishi',
    81: 'Mutaxassislardan har hafta taklif oling',
    82: ' Luxury',
    83: 'Bronlash',
    84: 'Qayta aloqa',
    85: ' Nega Lux Trips',
    86: ' Kontaktlar',
  },
};
