export const translate = {
  en: {
    0: 'Home',
    1: 'Luxury packages',
    2: 'Book with us',
    3: 'Why lux trips',
    4: 'Contact',
    5: 'Call me back',
    6: "Don't miss a chance to talk with us",
    7: 'Phone',
    8: 'Adress',
    9: 'Amir Temur 102, Tashkent, Uzbekistan',
    10: 'Email',
    11: ' Luxury packages',
    12: ' Book with us',
    13: ' Call me back',
    14: ' Why Lux Trips',
    15: ' Contact',
  },
  ru: {
    0: 'Главная',
    1: 'Люкс пакеты',
    2: 'Бронирование',
    3: 'Почему Lux Trip',
    4: 'Контакты',
    5: 'Связаться',
    6: 'Не усустите шанс связаться с нами',
    7: 'Телефон',
    8: 'Адрес',
    9: 'Узбекистан, Ташкент,Улица Амира Темура 102',
    10: 'Почта',
    11: 'Люкс пакеты',
    12: 'Бронирование',
    13: 'Связаться',
    14: 'Почему Lux Trip',
    15: 'Контакты',
  },
  uz: {
    0: 'Bosh saxifa',
    1: 'Luxury',
    2: 'Bronlash',
    3: 'Nega Lux Trips',
    4: 'Kontaktlar',
    5: 'Qayta aloqa',
    6: 'Biz bilan albatta bog`laning',
    7: 'Telefon',
    8: 'Adres',
    9: 'O`zbekiston, Toshkent, Amir Temur ko`chasi 102',
    10: 'Pochta',
    11: 'Luxury',
    12: 'Bronlash',
    13: 'Qayta aloqa',
    14: ' Nega Lux Trips',
    15: ' Kontaktlar',
  },
};
