export const translate = {
  en: {
    0: 'Home',
    1: 'Luxury packages',
    2: 'Book with us',
    3: 'Why lux trips',
    4: 'Contact',
    5: 'Call me back',
    6: 'Extra<br>ordinary',
    7: 'Places',
    8: 'Top Rated Experiances',
    9: 'World',
    10: 'Uzbekistan',
    11: 'Austria',
    12: 'Winter Park Ski Holiday',
    13: 'From',
    14: 'Peru',
    15: 'Machu Picchu',
    16: 'From',
    17: 'Croatia',
    18: 'Hvar',
    19: 'From',
    20: 'Jordan',
    21: 'Ad-Deir Abbey',
    22: 'From',
    23: 'Iceland',
    24: 'Goddafos Waterfall',
    25: 'From',
    26: 'Abkhazia',
    27: 'Blue Lake',
    28: 'From',
    29: 'Indonesia',
    30: 'Bali Island',
    31: 'From',
    32: 'Iceland',
    33: 'Seljalandsfoss Waterfall',
    34: 'From',
    35: 'Italy',
    36: 'Langa Grape Fields',
    37: 'From',
    38: 'Spain',
    39: 'Barcelona',
    40: 'From',
    41: 'Nepal',
    42: 'Everest',
    43: 'From',
    44: 'San Francisco',
    45: 'Golden Gate Bridge',
    46: 'From',
    47: 'Samarqand',
    48: 'Shahi Zinda',
    49: 'From',
    50: 'Toshkent',
    51: 'Timurid`s Museum',
    52: 'From',
    53: 'Xiva',
    54: 'Kalta Minor Minaret',
    55: 'From',
    56: 'Xiva',
    57: 'Ichan-Kala',
    58: 'From',
    59: 'Xiva',
    60: ' Mausoleum of Pahlavan Mahmud',
    61: 'From',
    62: 'Buxoro',
    63: ' Samanid`s Mausoleum',
    64: 'From',
    65: 'Buxoro',
    66: 'Minaret Kalyan',
    67: 'From',
    68: 'Samarqand',
    69: 'Registan',
    70: 'From',
    71: 'Samarqand',
    72: 'Ulugbek`s Observatory ',
    73: 'From',
    74: 'Toshkent',
    75: 'Romanov`s Palace',
    76: 'From',
    77: 'Toshkent',
    78: 'Toshkent Subway',
    79: 'From',
    80: 'Toshkent',
    81: 'Madrasah Kukeldash',
    82: 'From',
    83: 'Luxury Packages',
    84: 'View all',
    85: 'Best Winter Destinations ',
    86: "The world's most extraordinary places",
    87: 'New destinations for 2022',
    88: 'Your health is matter',
    89: 'Experiences Away From Crowd',
    90: 'Book With Us',
    91: 'Supercars',
    92: 'Hotels',
    93: 'Villas',
    94: 'Yachts',
    95: 'Helicopter',
    96: 'Air Jet',
    97: 'Why<br>Lux Trips',
    98: 'As Travel Designer, we know the ins and outs of travel from who to work with, where to go, when to book, and which restaurant provides the most authentic cuisine. ',
    99: 'Exclusive knowledge to provide the best of the best to clients',
    100: 'Our area of expertise ranges from luxury resorts and villas/chalets holiday bookings, private yacht and jet charters, to exclusive tours and personalized journey planning. ',
    101: 'We craft and plan unique itineraries tailored to customers’ interests and with strong attention to detail.',
    102: 'Help me plan a trip',
    103: 'Contact',
    104: ' Luxury packages',
    105: ' Book with us',
    106: ' Call me back',
    107: ' Why Lux Trips',
    108: ' Contact',
  },
  ru: {
    0: 'Гланая',
    1: 'Люкс пакеты',
    2: 'Бронирование',
    3: 'Почему Lux Trip',
    4: 'Контакты',
    5: 'Связаться',
    6: 'Красивые<br>яркие',
    7: 'Места',
    8: 'Популярные направления',
    9: 'Мир',
    10: 'Узбекистан',
    11: 'Австрия',
    12: 'Горнолыжный отдых в Зимнем парке',
    13: 'От',
    14: 'Перу',
    15: 'Мачу-Пикчу',
    16: 'От',
    17: 'Хорватия',
    18: 'Хвар',
    19: 'От',
    20: 'Иордания',
    21: 'Аббатство Ад-Дейр',
    22: 'От',
    23: 'Исландия',
    24: 'Водопад Годдафос',
    25: 'От',
    26: 'Абхазия',
    27: 'Голубое Озеро',
    28: 'От',
    29: 'Индонезия',
    30: 'Остров Бали',
    31: 'От',
    32: 'Исландия',
    33: 'Водопад Сельяландсфосс',
    34: 'От',
    35: 'Италия',
    36: 'Виноградные поля Ланга',
    37: 'От',
    38: 'Испания',
    39: 'Барселона',
    40: 'От',
    41: 'Непал',
    42: 'Эверест',
    43: 'От',
    44: 'Сан-Франциско',
    45: 'Мост Золотые Ворота',
    46: 'От',
    47: 'Самарканд',
    48: 'Шахи Зинда',
    49: 'От',
    50: 'Ташкент',
    51: 'Музей Тимуридов',
    52: 'От',
    53: 'Хива',
    54: 'Минарет Кальта-Минор',
    55: 'От',
    56: 'Хива',
    57: 'Ичан-Кала',
    58: 'От',
    59: 'Хива',
    60: 'Мавзолей Пахлаван Махмуда',
    61: 'От',
    62: 'Бухара',
    63: 'Мавзолей Самонидов',
    64: 'От',
    65: 'Бухара',
    66: 'Минарет Калян',
    67: 'От',
    68: 'Самарканд',
    69: 'Регистан',
    70: 'От',
    71: 'Самарканд',
    72: 'Обсерватория Улугбека',
    73: 'От',
    74: 'Ташкент',
    75: 'Дворец Романовых',
    76: 'От',
    77: 'Ташкент',
    78: 'Ташкентское метро',
    79: 'От',
    80: 'Ташкент',
    81: 'Медресе Кукельдаш',
    82: 'От',
    83: 'Люкс пакеты',
    84: 'Больше',
    85: 'Лучшие зимние направления',
    86: 'Самые необычные места мира',
    87: 'Новые направления на 2022 год',
    88: 'Ваше здоровье имеет значение',
    89: 'Впечатления в полном уединении',
    90: 'Бронирование',
    91: 'Суперкар',
    92: 'Отели',
    93: 'Виллы',
    94: 'Яхты',
    95: 'Вертолет',
    96: 'Боинг',
    97: 'Почему<br>Lux Trips',
    98: 'Как дизайнер путешествий, мы знаем все тонкости путешествия, с кем работать, куда идти, когда бронировать столик и в каком ресторане подают самую аутентичную кухню',
    99: 'Эксклюзивные знания, чтобы предоставить клиентам лучшее из лучшего',
    100: 'Наша область адаптивных возможностей варьируется от бронирования роскошных курортов и вилл / шале, частных яхт и чартеров самолетов до эксклюзивных туров и индивидуального планирования путешествий',
    101: 'Мы разрабатываем и планируем уникальные маршруты с учетом интересов клиентов и с большим вниманием к деталям.',
    102: 'Получить консультацию',
    103: 'Контакт',
    104: 'Люкс пакеты',
    105: 'Бронирование',
    106: 'Связаться',
    107: 'Почему Lux Trip',
    108: 'Контакты',
  },
  uz: {
    0: 'Bosh saxifa',
    1: 'Luxury',
    2: 'Bronlash',
    3: 'Nega Lux Trips',
    4: 'Kontaktlar',
    5: 'Qayta aloqa',
    6: 'Chiroyli<br>Garoyib',
    7: 'Joylar',
    8: 'Mashxur joylar',
    9: 'Dunyo',
    10: 'O`zbekiston',
    11: 'Avstriya',
    12: 'Qishgi parkda tatil',
    13: 'Boshlanishi',
    14: 'Peru',
    15: 'Machu Pikchu',
    16: 'Boshlanishi',
    17: 'Xorvatiya',
    18: 'Hvar',
    19: 'Boshlanishi',
    20: 'Iordan',
    21: 'Ad-Deir',
    22: 'Boshlanishi',
    23: 'Islandiya',
    24: 'Goddafos sharsharasi',
    25: 'Boshlanishi',
    26: 'Abxaziya',
    27: 'Blue Ko`l',
    28: 'Boshlanishi',
    29: 'Indonesia',
    30: 'Bali Oroli',
    31: 'Boshlanishi',
    32: 'Islandiya',
    33: 'Seljalandsfoss sharsharasi',
    34: 'Boshlanishi',
    35: 'Italiya',
    36: 'Langa Uzum Dalalari',
    37: 'Boshlanishi',
    38: 'Ispaniya',
    39: 'Barselona',
    40: 'Boshlanishi',
    41: 'Nepal',
    42: 'Everest',
    43: 'Boshlanishi',
    44: 'San-Fransisko',
    45: "Oltin Darvoza ko'prigi",
    46: 'Boshlanishi',
    47: 'Samarqand',
    48: 'Shohi Zinda',
    49: 'Boshlanishi',
    50: 'Toshkent',
    51: 'Temuridlar Muzeyi',
    52: 'Boshlanishi',
    53: 'Xiva',
    54: 'Kalta-Minor',
    55: 'Boshlanishi',
    56: 'Xiva',
    57: 'Ichon-Qal`a',
    58: 'Boshlanishi',
    59: 'Xiva',
    60: 'Pahlavon Mahmud maqbarasi',
    61: 'Boshlanishi',
    62: 'Buxoro',
    63: 'Somoniylar maqbarasi',
    64: 'Boshlanishi',
    65: 'Buxoro',
    66: 'Qalan Minorasi',
    67: 'Boshlanishi',
    68: 'Samarqand',
    69: 'Registon',
    70: 'Boshlanishi',
    71: 'Samarqand',
    72: 'Ulug‘bek Rasadxonasi',
    73: 'Boshlanishi',
    74: 'Toshkent',
    75: 'Romanovlar Saroyi',
    76: 'Boshlanishi',
    77: 'Toshkent',
    78: 'Toshkent Metrosi',
    79: 'Boshlanishi',
    80: 'Toshkent',
    81: 'Koʻkeldosh Madrasasi',
    82: 'Boshlanishi',
    83: 'Luxury',
    84: 'Batafsil',
    85: 'Eng yaxshi qishgi yo`nalishlar',
    86: "Dunyoning eng g'ayrioddiy joylari",
    87: "2022 yil uchun yangi yo'nalishlar",
    88: "Sizning sog'ligingiz muhim",
    89: "Yolg`izlikda bo'lgan vaqt",
    90: 'Bronlash',
    91: 'Superkarlar',
    92: 'Otel',
    93: 'Villa',
    94: 'Yaxta',
    95: 'Vertolyot',
    96: 'Boing',
    97: 'Nega<br>Lux Trips',
    98: 'Sayohat dizayneri sifatida biz kim bilan ishlash, qaerga borish, qachon bron qilish va qaysi restoranda eng haqiqiy taomni taqdim etishi kabi sayohatning nozik va nozik tomonlarini bilamiz.',
    99: 'Mijozlarga eng yaxshisini taqdim etish uchun eksklyuziv bilim',
    100: 'Bizning tajriba sohamiz hashamatli kurortlar va villalar/chaletlar ta`tillarini bron qilish, xususiy yaxta va reaktiv charterlar, eksklyuziv sayohatlar va shaxsiy sayohatni rejalashtirishgacha.',
    101: 'Biz mijozlarning qiziqishlariga moslashtirilgan va tafsilotlarga katta e`tibor bergan holda noyob marshrutlarni ishlab chiqamiz va rejalashtiramiz',
    102: 'To`liq malumot olish',
    103: 'Kontakt',
    104: ' Luxury',
    105: 'Bronlash',
    106: 'Qayta aloqa',
    107: ' Nega Lux Trips',
    108: ' Kontaktlar',
  },
};
